// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSnc_Gdlu58H-r7hRxh5QqM5c0H_aneNM',
    appId: '1:415275215923:web:b969632a10860911018746',
    messagingSenderId: '415275215923',
    projectId: 'chatik-for-users',
    authDomain: 'chatik-for-users.firebaseapp.com',
    storageBucket: 'chatik-for-users.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_J2PSHYG4bFIIox73RX3ImL8wHsr76kA',
    appId: '1:415275215923:android:a95806b772af0050018746',
    messagingSenderId: '415275215923',
    projectId: 'chatik-for-users',
    storageBucket: 'chatik-for-users.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDsscLiyzabzlUo28nlQXvgf-3yV857Xw',
    appId: '1:415275215923:ios:963016e4b03259de018746',
    messagingSenderId: '415275215923',
    projectId: 'chatik-for-users',
    storageBucket: 'chatik-for-users.appspot.com',
    iosBundleId: 'com.example.chatikForUsers',
  );
}
